export const productData = [
  {
    id: 1,
    image:
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    alt: "Co-founders Agreement visual",
    section:"Business Documents",
    title: "Co-founders Agreement",
    description:"A co-founder Agreement allows you to set out the equity ownership, initial investments and responsibilities of each Co-founder.",
      features:[
        "Co-founder details",
        "Work/project scope",
        "Responsibilities of each founder",
        "Intellectual property clause",
        "Confidentiality clause",
        "Non-compete clause",
        "Dissolution, resignation and dissolution ",
      ],
    price: 100000,
  },
  {
    id: 2,
    image:
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    alt: "Shareholders Agreement",
    section:"Business Documents",
    title: "Shareholders agreement ",
    description:"A shareholders Agreement will help you govern the relationship between your company shareholders. Although you and your partners are on good terms now, sometimes running a company will strain on the relationship, therefore it’s better to prepare from the onset and protect your interests and the company.",
      features:[
        "Shareholder details",
        "Powers and responsibilities of a shareholder",
        "Restrictions on transfer and assignment to third parties",
        "How many shares  to be held",
        "Dispute resolution",
        "Exit strategy",
      ],
    price: 100000,
  },
  {
    id: 3,
    image:
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    alt: "Business Plan",
    section:"Business Documents",
    title: "Business Plan",
    description:"A document setting out a business's future objectives and strategies for achieving them.",
      features:[
        "Your business overview",
        "Product or service",
        "Problem and solution",
        "Business management",
        "Market analysis and strategy",
        "Revenue analysis",
      ],
    price: 50000,
  },
  {
    id: 4,
    image:
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    alt: "Non-Disclosure Agreement (NDA)",
    section:"Business Documents",
    title: "Non-Disclosure Agreement (NDA)",
    description:"A Non-disclosure agreement is a legal document that forbids a recipient of information from disclosing that information to any person or entity. Before sharing any information that is so important to your company it is crucial that you sign it.",
      features:[
        "Description of the confidential information",
        "Rights and obligations",
        "Protection of the information",
        "Circumstances where disclosure is permitted",
        "Effects of breach",
      ],
    price: 50000,
  },
  {
    id: 5,
    image:
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    alt: "Service Contract",
    section:"Business Documents",
    title: "Service Contract",
    description:"A contract used between a service provider and a client (or customer) that outlines the exchange of services for compensation.",
      features:[
        "Performance  of the services",
        "Consideration/payment ",
        "Location ",
        "Clients obligations",
        "Service provider obligations",
        "Warranties and indemnities",
        "Termination",
        "Dispute resolution",
      ],
    price: 50000,
  },
  {
    id: 6,
    image:
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    alt: "Board resolution",
    section:"Business Documents",
    title: "Board resolution",
    description:"A Resolution is a formal means by which decisions are made by a meeting of company, Resolutions a drafted to legally express the company decision and can be registered with URSB.",
      features:[
        "Details of the agreed on points",
        "Registration",
        "Signatories",
      ],
    price: 50000,
  },
  {
    id: 7,
    image:
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    alt: "Joint venture Agreements",
    section:"Business Documents",
    title: "Joint venture Agreements",
    description:"A joint venture is a contract between two or more parties who want to do business together for a period of time. Instead of forming a company, or partnership if your intention is to join with another party and have an equal stake in the venture. You can choose to enter a Joint venture Agreement.",
      features:[
        "Business objectives",
        "Responsibilities of each party",
        "Distribution of cost",
        "Profit sharing",
        "Liability ",
        "Termination",
        "Dispute resolution",
      ],
    price: 100000,
  },

  {
    id: 8,
    image:
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    alt: "Employment agreement",
    section:"Employment Documents",
    title: "Employment agreement",
    description:"Employment Agreement is an essential document when hiring employees for your business. They are not only necessary for your legal protection; they can help set the tone and feel of your business. It also helps formalize the relationship between employee an employer which enhances professional and positive work.",
      features:[
        "Scope of work",
        "Employee obligations",
        "Remuneration",
        "Benefits",
        "Confidentiality clause",
        "Share scheme ",
        "Termination ",
        "Dispute resolution",
      ],
    price: 150000,
  },
  {
    id: 9,
    image:
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    alt: "Casual worker agreements (part time)",
    section:"Employment Documents",
    title: "Casual worker agreements (part time) ",
    description:"This Casual Worker's Contract is for use where there is no mutuality of obligation and no continuing employment relationship between assignments.",
      features:[
        "Work description", 
        "Working ours",
        "Payments and benefits",
        "Termination",
      ],
    price: 100000,
  },
  {
    id: 10,
    image:
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    alt: "Contractor agreement ",
    section:"Employment Documents",
    title: "Contractor agreement ",
    description:"An independent Contractor Agreement is a written contract that spells out the terms of the working arrangement between a contractor and client; it includes a description of services, terms of service and payment details among others.",
      features:[
        "Service performance",
        "Consideration",
        "Payment & expenses",
        "Confidentiality",
        "Intellectual property",
        "Termination",
      ],
    price: 100000,
  },
  {
    id: 11,
    image:
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    alt: "Termination deed/letter",
    section:"Employment Documents",
    title: "Termination deed/letter",
    description:"A termination letter is one to be used when terminating an employee, this is to be signed by the employee finalizing all outstanding issues between the employer and employee. This deed will allow you with future issues smoothly, such as contractual claims or claims arising out of the termination of employment.",
      features:[
        "Employment obligations clause",
        "Restraint of trade clause",
        "Restraint on future claims or disputes",
        "Severance and other entitlements ",
      ],
    price: 100000,
  },
];
